### ISSUE TITLE
Use anki-persistence to save and load in any platform

### ISSUE THREAD

**Issue by helq** [pigoz/anki-canvas#4]
So, more and more developers are working with anki cards and javascript which is pretty cool. I've come across this project that allows to save data between the front and back cards for _any_ anki platform:

https://github.com/SimonLammer/anki-persistence

It would be nice if you could use it for anki-canvas. For what I gather from your code, anki-persistence would replace your "storage.ts".

**Comment by pigoz** [comment]
Thanks for letting me know about that project: it will certainly be useful.

From what I understand from their code, they are supporting Anki 2.0 as well, while mine only works on Anki 2.1 (since I hardcoded a check for a QtWebEngine user agent), web, Android and iOS – although that should be easily fixable.

Since my code seems far simpler, they are not publishing theirs as an npm package, and I'd have to write TypeScript typings anyway, I'd rather keep my NIH'd implementation and improve it.

**Comment by helq** [comment]
Cool. I suggested using anki-persistence because it's a project that has been tested on all anki platforms and it's likely to keep up with any change, if there is, in all anki platforms. But I suppose it's just easier to copy the important bits into the project.

If you modify your code accordingly to theirs, don't forget to add them to acknowledgements and follow any change in their code.

Good luck with the next release. :D

**Comment by pigoz** [comment]
I would have switched if they released it as a npm package to be honest!
